name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    # runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to DigitalOcean Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract timestamp
        id: timestamp
        run: echo "::set-output name=ts::$(date +'%y%m%d.%H%M')"

      - name: Build and push API Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ vars.REGISTRY }}/${{ vars.IMAGE_NAME }}:latest
            ${{ vars.REGISTRY }}/${{ vars.IMAGE_NAME }}:${{ github.ref_name }}-${{ steps.timestamp.outputs.ts }}-${{ github.sha }}

# Update ArgoCD application configuration

      - name: Set up yq
        run: |
          if ! command -v yq &> /dev/null; then
            echo "yq not found, installing..."
            wget https://github.com/mikefarah/yq/releases/download/v4.44.2/yq_linux_amd64 -O yq
            chmod +x yq
            echo "${{ github.workspace }}/yq" >> $GITHUB_PATH
          else
            echo "yq is already installed"
          fi

      - name: Clone config repository
        uses: actions/checkout@v4
        with:
          repository: jetdream/tf-cluster
          ref: main
          path: .tf-cluster
          token: ${{ secrets.TF_CLUSTER_GITHUB_KEY }}

      - name: Update kustomization.yaml for dev
        run: |
          cd .tf-cluster/config/overlays/dev
          yq e '.images[] |= select(.name == "${{ vars.REGISTRY }}/${{ vars.IMAGE_NAME }}").newTag = "${{ github.ref_name }}-${{ steps.timestamp.outputs.ts }}-${{ github.sha }}"' -i kustomization.yaml

      - name: Commit and push changes
        run: |
          cd .tf-cluster
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add config/overlays/dev/kustomization.yaml 
          git commit -m "Update image tags to ${{ github.sha }}"
          git push
