name: CI Pipeline

on:
  push:
    branches:
      - main
    paths:
      - '**/*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to DigitalOcean Container Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login registry.digitalocean.com -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t registry.digitalocean.com/targetflow/webhook-nats-gateway:latest .
          docker push registry.digitalocean.com/targetflow/webhook-nats-gateway:latest
