name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev
      - staging

jobs:
  build-and-push:
    # runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to DigitalOcean Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push API Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ vars.REGISTRY }}/${{ vars.IMAGE_NAME }}:latest
            ${{ vars.REGISTRY }}/${{ vars.IMAGE_NAME }}:${{ github.ref_name }}-${{ github.sha }}

# Update ArgoCD application configuration

      - name: Check if yq is installed
        id: check_yq
        run: |
          if ! command -v yq &> /dev/null; then
            echo "yq not found"
            echo "install_yq=true" >> $GITHUB_ENV
          else
            echo "yq is already installed"
            echo "install_yq=false" >> $GITHUB_ENV
          fi

      - name: Install yq
        if: env.install_yq == 'true'
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.44.2/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Clone config repository
        uses: actions/checkout@v4
        with:
          repository: jetdream/tf-cluster
          ref: main
          path: .tf-cluster

      - name: Update kustomization.yaml for dev
        run: |
          cd .tf-cluster/config/overlays/dev
          yq e '.images[] |= select(.name == "registry.digitalocean.com/targetflow/webhook-nats-gateway").newTag = "dev-${{ github.sha }}"' -i kustomization.yaml

      - name: Commit and push changes
        run: |
          cd .tf-cluster
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add config/overlays/dev/kustomization.yaml 
          git commit -m "Update image tags to ${{ github.sha }}"
          git push

