name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev
      - staging

jobs:
  build-and-push:
    # runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to DigitalOcean Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push API Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ vars.REGISTRY }}/${{ vars.IMAGE_NAME }}:latest
            ${{ vars.REGISTRY }}/${{ vars.IMAGE_NAME }}:${{ github.ref_name }}-${{ github.sha }}

